import { defineConfig } from 'vite'
import { svelte, vitePreprocess } from '@sveltejs/vite-plugin-svelte'
import { join } from 'path'
import builtins from 'builtin-modules'

const prod = process.argv[2] === 'production'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

// https://vitejs.dev/config/
export default defineConfig({
  esbuild: {
    banner,
  },
  build: {
    lib: {
      entry: 'src/main.ts',
      formats: ['cjs'],
    },
    rollupOptions: {
      output: {
        entryFileNames: '[name].js',
        assetFileNames: (chunkInfo) =>
          chunkInfo.name === 'style.css' ? 'styles.css' : '[name].[ext]',
      },
      external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
      ],
    },
    outDir: '.',
  },
  resolve: {
    alias: {
      src: join(__dirname, 'src'),
    },
  },
  optimizeDeps: {
    exclude: ['obsidian'],
  },
  plugins: [
    svelte({
      preprocess: vitePreprocess(),
      compilerOptions: { css: 'external' },
    }),
  ],
})
