name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Rename artifact
        run: mv plugin.zip ${{ github.event.repository.name }}-${{ steps.version.outputs.tag }}.zip

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: /home/runner/work/obsidian-super-plan/obsidian-super-plan/artifact
          draft: true
