name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package
          path: download

      - name: Display structure of downloaded files
        run: cd download && ls -R

      - name: Rename artifact
        run:
          unzip download/plugin.zip -d download && rm download/plugin.zip

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: download
          draft: true
